import type { VibeOption } from '@/types';

export const DUMMY_PLAYERS = [
  { id: '1', username: 'FireStarter', isHost: true, joinedAt: new Date().toISOString() },
  { id: '2', username: 'CoolCat', isHost: false, joinedAt: new Date().toISOString() },
  { id: '3', username: 'PartyKing', isHost: false, joinedAt: new Date().toISOString() },
  { id: '4', username: 'NightOwl', isHost: false, joinedAt: new Date().toISOString() },
];

export const DUMMY_QUESTIONS = {
  party: [
    // Party Fragen (250)
    'Wer würde am ehesten auf einer Party einschlafen?',
    'Wer würde am ehesten die Karaoke-Maschine monopolisieren?',
    'Wer würde am ehesten auf dem Tisch tanzen?',
    'Wer würde am ehesten vergessen, wo sie geparkt haben?',
    'Wer würde am ehesten zu viel Alkohol trinken?',
    'Wer würde am ehesten als Erster auf der Tanzfläche sein?',
    'Wer würde am ehesten den DJ nerven?',
    'Wer würde am ehesten die Party crashen?',
    'Wer würde am ehesten Shots für alle bestellen?',
    'Wer würde am ehesten am nächsten Tag nichts mehr wissen?',
    'Wer würde am ehesten mit einem Fremden nach Hause gehen?',
    'Wer würde am ehesten im Club einschlafen?',
    'Wer würde am ehesten sein Handy verlieren?',
    'Wer würde am ehesten eine Runde für alle ausgeben?',
    'Wer würde am ehesten beim Trinkspielen schummeln?',
    'Wer würde am ehesten als Letzter die Party verlassen?',
    'Wer würde am ehesten betrunken peinliche Nachrichten schreiben?',
    'Wer würde am ehesten auf der Toilette einschlafen?',
    'Wer würde am ehesten seine Schuhe verlieren?',
    'Wer würde am ehesten betrunken weinen?',
    'Wer würde am ehesten eine Schlägerei anfangen?',
    'Wer würde am ehesten betrunken Pizza bestellen?',
    'Wer würde am ehesten über den eigenen Witz lachen?',
    'Wer würde am ehesten seinen Ex anrufen?',
    'Wer würde am ehesten betrunken tanzen wie niemand zuschaut?',
    'Wer würde am ehesten den Barkeeper anbaggern?',
    'Wer würde am ehesten alle Partys organisieren?',
    'Wer würde am ehesten die Musik zu laut aufdrehen?',
    'Wer würde am ehesten betrunken kochen?',
    'Wer würde am ehesten seinen Geldbeutel vergessen?',
    'Wer würde am ehesten einen Kater leugnen?',
    'Wer würde am ehesten betrunken Geheimnisse ausplaudern?',
    'Wer würde am ehesten beim Limbo gewinnen?',
    'Wer würde am ehesten die Party mit Drama beenden?',
    'Wer würde am ehesten auf der Party verschwinden?',
    'Wer würde am ehesten den ganzen Abend am Buffet stehen?',
    'Wer würde am ehesten einen Trinkspruch halten?',
    'Wer würde am ehesten betrunken schwimmen gehen?',
    'Wer würde am ehesten die Nachbarn aufwecken?',
    'Wer würde am ehesten einen Drink verschütten?',
    'Wer würde am ehesten die After-Party organisieren?',
    'Wer würde am ehesten beim Bierpong dominieren?',
    'Wer würde am ehesten betrunken Selfies machen?',
    'Wer würde am ehesten die Playlist übernehmen?',
    'Wer würde am ehesten am nächsten Tag zur Arbeit fehlen?',
    'Wer würde am ehesten den Taxifahrer vollquatschen?',
    'Wer würde am ehesten beim Flaschendrehen rot werden?',
    'Wer würde am ehesten eine neue Freundschaft schließen?',
    'Wer würde am ehesten betrunken Sport treiben?',
    'Wer würde am ehesten den Gastgeber umarmen?',
    'Wer würde am ehesten eine spontane Rede halten?',
    'Wer würde am ehesten betrunken Online-Shopping machen?',
    'Wer würde am ehesten alle zum Lachen bringen?',
    'Wer würde am ehesten betrunken kochen und es verbrennen?',
    'Wer würde am ehesten am Pool einschlafen?',
    'Wer würde am ehesten die Feuerwerk zünden?',
    'Wer würde am ehesten als Wingman agieren?',
    'Wer würde am ehesten betrunken singen?',
    'Wer würde am ehesten die ganze Nacht durchtanzen?',
    'Wer würde am ehesten einen VIP-Bereich organisieren?',
    'Wer würde am ehesten den Grill anwerfen?',
    'Wer würde am ehesten betrunken philosophieren?',
    'Wer würde am ehesten alle Namen vergessen?',
    'Wer würde am ehesten eine Mottoparty schmeißen?',
    'Wer würde am ehesten beim Tanzen stürzen?',
    'Wer würde am ehesten die Stimmung retten?',
    'Wer würde am ehesten betrunken in den Pool springen?',
    'Wer würde am ehesten die Cocktails mixen?',
    'Wer würde am ehesten einen Prominenten erkennen?',
    'Wer würde am ehesten betrunken Auto fahren wollen?',
    'Wer würde am ehesten die Dekoration loben?',
    'Wer würde am ehesten beim Trinkspiel aufgeben?',
    'Wer würde am ehesten alle Fotos machen?',
    'Wer würde am ehesten die Party früh verlassen?',
    'Wer würde am ehesten neue Leute vorstellen?',
    'Wer würde am ehesten den Abend dokumentieren?',
    'Wer würde am ehesten alle Witze erzählen?',
    'Wer würde am ehesten betrunken Yoga machen?',
    'Wer würde am ehesten die Getränke auffüllen?',
    'Wer würde am ehesten spontan verreisen wollen?',
    'Wer würde am ehesten beim Karaoke glänzen?',
    'Wer würde am ehesten die Stimmungsmusik auflegen?',
    'Wer würde am ehesten betrunken Komplimente verteilen?',
    'Wer würde am ehesten die Snacks mitbringen?',
    'Wer würde am ehesten am nächsten Tag joggen?',
    'Wer würde am ehesten eine Challenge starten?',
    'Wer würde am ehesten betrunken streiten?',
    'Wer würde am ehesten die Rechnung splitten?',
    'Wer würde am ehesten alle zum Anstoßen versammeln?',
    'Wer würde am ehesten betrunken meditieren?',
    'Wer würde am ehesten das Taxi bestellen?',
    'Wer würde am ehesten die Garderobe bewachen?',
    'Wer würde am ehesten betrunken Poker spielen?',
    'Wer würde am ehesten am Morgen danach kochen?',
    'Wer würde am ehesten eine Diashow zeigen?',
    'Wer würde am ehesten betrunken wandern gehen?',
    'Wer würde am ehesten alle zum Mitsingen animieren?',
    'Wer würde am ehesten das perfekte Outfit tragen?',
    'Wer würde am ehesten betrunken Geschichten erfinden?',
    'Wer würde am ehesten die Lichter dimmen?',
    'Wer würde am ehesten auf dem Sofa einschlafen?',
    'Wer würde am ehesten den Kamin anzünden?',
    'Wer würde am ehesten betrunken malen?',
    'Wer würde am ehesten alle Namen merken?',
    'Wer würde am ehesten die Spiele erklären?',
    'Wer würde am ehesten betrunken basteln?',
    'Wer würde am ehesten die Musikbox mitbringen?',
    'Wer würde am ehesten am längsten wach bleiben?',
    'Wer würde am ehesten betrunken lesen?',
    'Wer würde am ehesten die Kerzen anzünden?',
    'Wer würde am ehesten alle umarmen?',
    'Wer würde am ehesten betrunken backen?',
    'Wer würde am ehesten die Fotos sortieren?',
    'Wer würde am ehesten am nächsten Tag Sport machen?',
    'Wer würde am ehesten den Brunch organisieren?',
    'Wer würde am ehesten betrunken aufräumen?',
    'Wer würde am ehesten die Reste einpacken?',
    'Wer würde am ehesten alle nach Hause bringen?',
    'Wer würde am ehesten betrunken putzen?',
    'Wer würde am ehesten die nächste Party planen?',
    'Wer würde am ehesten Spiele erfinden?',
    'Wer würde am ehesten betrunken duschen?',
    'Wer würde am ehesten die Blumen gießen?',
    'Wer würde am ehesten alle Nummern speichern?',
    'Wer würde am ehesten betrunken bügeln?',
    'Wer würde am ehesten die Musik leiser machen?',
    'Wer würde am ehesten am Fenster rauchen?',
    'Wer würde am ehesten betrunken stricken?',
    'Wer würde am ehesten den Müll rausbringen?',
    'Wer würde am ehesten alle Geschichten kennen?',
    'Wer würde am ehesten betrunken nähen?',
    'Wer würde am ehesten die Tür aufhalten?',
    'Wer würde am ehesten alle beruhigen?',
    'Wer würde am ehesten betrunken puzzeln?',
    'Wer würde am ehesten die Heizung regulieren?',
    'Wer würde am ehesten am Balkon stehen?',
    'Wer würde am ehesten betrunken zeichnen?',
    'Wer würde am ehesten die Fenster öffnen?',
    'Wer würde am ehesten alle motivieren?',
    'Wer würde am ehesten betrunken tanzen lernen?',
    'Wer würde am ehesten die Gläser spülen?',
    'Wer würde am ehesten einen Toast aussprechen?',
    'Wer würde am ehesten betrunken meditieren wollen?',
    'Wer würde am ehesten die Tischdecke retten?',
    'Wer würde am ehesten alle Drinks probieren?',
    'Wer würde am ehesten betrunken Sprachen üben?',
    'Wer würde am ehesten den Gastgeber loben?',
    'Wer würde am ehesten alle unterhalten?',
    'Wer würde am ehesten betrunken Sport schauen?',
    'Wer würde am ehesten die Musik wechseln?',
    'Wer würde am ehesten am Eingang stehen?',
    'Wer würde am ehesten betrunken debattieren?',
    'Wer würde am ehesten die Gäste begrüßen?',
    'Wer würde am ehesten alle Getränke kennen?',
    'Wer würde am ehesten betrunken flirten üben?',
    'Wer würde am ehesten die Stühle aufstellen?',
    'Wer würde am ehesten als DJ auflegen wollen?',
    'Wer würde am ehesten betrunken Film schauen?',
    'Wer würde am ehesten die Tische decken?',
    'Wer würde am ehesten alle zum Schweigen bringen?',
    'Wer würde am ehesten betrunken planen?',
    'Wer würde am ehesten die Servietten falten?',
    'Wer würde am ehesten eine Anekdote erzählen?',
    'Wer würde am ehesten betrunken träumen?',
    'Wer würde am ehesten die Kissen verteilen?',
    'Wer würde am ehesten alle fotografieren?',
    'Wer würde am ehesten betrunken malen wollen?',
    'Wer würde am ehesten den Kühlschrank füllen?',
    'Wer würde am ehesten Komplimente verteilen?',
    'Wer würde am ehesten betrunken basteln wollen?',
    'Wer würde am ehesten die Bar aufbauen?',
    'Wer würde am ehesten alle integrieren?',
    'Wer würde am ehesten betrunken schreiben?',
    'Wer würde am ehesten die Lichter steuern?',
    'Wer würde am ehesten Geschenke mitbringen?',
    'Wer würde am ehesten betrunken kochen wollen?',
    'Wer würde am ehesten die Tür schließen?',
    'Wer würde am ehesten alle überraschen?',
    'Wer würde am ehesten betrunken singen wollen?',
    'Wer würde am ehesten die Jacken verstauen?',
    'Wer würde am ehesten Tipps geben?',
    'Wer würde am ehesten betrunken lernen wollen?',
    'Wer würde am ehesten die Schuhe ordnen?',
    'Wer würde am ehesten allen helfen?',
    'Wer würde am ehesten betrunken arbeiten wollen?',
    'Wer würde am ehesten die Gläser polieren?',
    'Wer würde am ehesten Ratschläge erteilen?',
    'Wer würde am ehesten betrunken Sport machen wollen?',
    'Wer würde am ehesten die Teller verteilen?',
    'Wer würde am ehesten alle einladen?',
    'Wer würde am ehesten betrunken reisen wollen?',
    'Wer würde am ehesten die Bestecke sortieren?',
    'Wer würde am ehesten als Moderator agieren?',
    'Wer würde am ehesten betrunken organisieren?',
    'Wer würde am ehesten die Kerzen löschen?',
    'Wer würde am ehesten alle ermutigen?',
    'Wer würde am ehesten betrunken dekorieren?',
    'Wer würde am ehesten die Musik ausmachen?',
    'Wer würde am ehesten Reden schwingen?',
    'Wer würde am ehesten betrunken aufstehen?',
    'Wer würde am ehesten die Fenster schließen?',
    'Wer würde am ehesten alle verabschieden?',
    'Wer würde am ehesten betrunken plaudern?',
    'Wer würde am ehesten die Heizung abstellen?',
    'Wer würde am ehesten für Stimmung sorgen?',
    'Wer würde am ehesten betrunken aufbleiben?',
    'Wer würde am ehesten die Klimaanlage regeln?',
    'Wer würde am ehesten alle beschenken?',
    'Wer würde am ehesten betrunken kuscheln?',
    'Wer würde am ehesten die Vorhänge zuziehen?',
    'Wer würde am ehesten alles dokumentieren?',
    'Wer würde am ehesten betrunken tanzen wollen?',
    'Wer würde am ehesten die Türen abschließen?',
    'Wer würde am ehesten alle zusammenbringen?',
    'Wer würde am ehesten betrunken reden wollen?',
    'Wer würde am ehesten die Alarmanlagen checken?',
    'Wer würde am ehesten Geheimnisse teilen?',
    'Wer würde am ehesten betrunken schlafen gehen?',
    'Wer würde am ehesten die letzte Runde ausgeben?',
    'Wer würde am ehesten alle trösten?',
    'Wer würde am ehesten die Afterparty starten?',
    'Wer würde am ehesten betrunken Fragen stellen?',
    'Wer würde am ehesten die Wohnung zeigen?',
    'Wer würde am ehesten alle beschützen?',
    'Wer würde am ehesten betrunken flüstern?',
    'Wer würde am ehesten die Bilder aufhängen?',
    'Wer würde am ehesten alle loben?',
    'Wer würde am ehesten betrunken schreien?',
    'Wer würde am ehesten die Möbel umstellen?',
    'Wer würde am ehesten alle feiern lassen?',
    'Wer würde am ehesten betrunken lachen?',
    'Wer würde am ehesten als letzter gehen?',
    'Wer würde am ehesten alle anfeuern?',
    'Wer würde am ehesten betrunken jubeln?',
    'Wer würde am ehesten die Gästeliste führen?',
    'Wer würde am ehesten alle inspirieren?',
    'Wer würde am ehesten betrunken klatschen?',
    'Wer würde am ehesten die Einladungen schreiben?',
  ],
  date_night: [
    'Wer würde am ehesten beim ersten Date zu viel reden?',
    'Wer würde am ehesten das Dessert bestellen?',
    'Wer würde am ehesten zu spät zum Date kommen?',
    'Wer würde am ehesten die Rechnung übernehmen?',
  ],
  family: [
    'Wer würde am ehesten das Familienessen organisieren?',
    'Wer würde am ehesten die besten Geschenke kaufen?',
    'Wer würde am ehesten den Familienurlaub planen?',
  ],
  spicy: [
    // Spicy Fragen (250)
    'Wer würde am ehesten in der Öffentlichkeit erwischt werden?',
    'Wer würde am ehesten eine Affäre haben?',
    'Wer würde am ehesten beim Lügen erwischt werden?',
    'Wer würde am ehesten einen One-Night-Stand haben?',
    'Wer würde am ehesten nackt schwimmen gehen?',
    'Wer würde am ehesten Nacktfotos verschicken?',
    'Wer würde am ehesten ein Sextape machen?',
    'Wer würde am ehesten auf einer Dating-App süchtig sein?',
    'Wer würde am ehesten eine heimliche Beziehung haben?',
    'Wer würde am ehesten fremdgehen?',
    'Wer würde am ehesten einen Stripclub besuchen?',
    'Wer würde am ehesten Sex im Büro haben?',
    'Wer würde am ehesten in einem Aufzug knutschen?',
    'Wer würde am ehesten Handschellen im Schlafzimmer benutzen?',
    'Wer würde am ehesten auf einer Party verschwinden um zu knutschen?',
    'Wer würde am ehesten Sex am Strand haben?',
    'Wer würde am ehesten eine Dreierbeziehung eingehen?',
    'Wer würde am ehesten bei Wahrheit oder Pflicht immer Pflicht wählen?',
    'Wer würde am ehesten seinen Schwarm direkt ansprechen?',
    'Wer würde am ehesten beim Flirten rot werden?',
    'Wer würde am ehesten einen Ex zurücknehmen?',
    'Wer würde am ehesten betrunken seinen Ex anrufen?',
    'Wer würde am ehesten die wildesten Fantasien haben?',
    'Wer würde am ehesten in einem Auto Sex haben?',
    'Wer würde am ehesten auf einer Hochzeit flirten?',
    'Wer würde am ehesten sich in den Lehrer verlieben?',
    'Wer würde am ehesten heimlich verliebt sein?',
    'Wer würde am ehesten den Partner der Freundin attraktiv finden?',
    'Wer würde am ehesten Dessous als Geschenk kaufen?',
    'Wer würde am ehesten in einer Umkleide erwischt werden?',
    'Wer würde am ehesten einen Sugar Daddy haben?',
    'Wer würde am ehesten für Geld strippen?',
    'Wer würde am ehesten auf Tinder am aktivsten sein?',
    'Wer würde am ehesten den ersten Schritt machen?',
    'Wer würde am ehesten in einer offenen Beziehung sein?',
    'Wer würde am ehesten Sex im Flugzeug haben?',
    'Wer würde am ehesten FKK-Urlaub machen?',
    'Wer würde am ehesten Lovoo oder Bumble benutzen?',
    'Wer würde am ehesten beim Küssen die Augen offen haben?',
    'Wer würde am ehesten den peinlichsten Flirtversuch starten?',
    'Wer würde am ehesten jemanden ghosten?',
    'Wer würde am ehesten geghosted werden?',
    'Wer würde am ehesten Friends with Benefits haben?',
    'Wer würde am ehesten in Vegas spontan heiraten?',
    'Wer würde am ehesten seinen Partner stalken?',
    'Wer würde am ehesten eifersüchtig sein?',
    'Wer würde am ehesten eine Fernbeziehung führen?',
    'Wer würde am ehesten beim ersten Date schon küssen?',
    'Wer würde am ehesten eine Affäre verzeihen?',
    'Wer würde am ehesten Sex im Wald haben?',
    'Wer würde am ehesten verführerische Nachrichten schreiben?',
    'Wer würde am ehesten Roleplay im Bett mögen?',
    'Wer würde am ehesten einen Promi daten wollen?',
    'Wer würde am ehesten den besten Kuss geben?',
    'Wer würde am ehesten am lautesten im Bett sein?',
    'Wer würde am ehesten Spielzeug benutzen?',
    'Wer würde am ehesten eine Bucket List für Dates haben?',
    'Wer würde am ehesten im Kino knutschen?',
    'Wer würde am ehesten Sex im Hotel haben?',
    'Wer würde am ehesten beim Dirty Talk verlegen werden?',
    'Wer würde am ehesten einen Liebhaber in jeder Stadt haben?',
    'Wer würde am ehesten Blind Dates lieben?',
    'Wer würde am ehesten den Partner der Eltern hassen?',
    'Wer würde am ehesten heimlich Pornos schauen?',
    'Wer würde am ehesten eine Beziehung beenden per SMS?',
    'Wer würde am ehesten am schnellsten Ich liebe dich sagen?',
    'Wer würde am ehesten in einer Beziehung dominant sein?',
    'Wer würde am ehesten submissiv sein?',
    'Wer würde am ehesten den besten Massage geben?',
    'Wer würde am ehesten Strip-Poker spielen?',
    'Wer würde am ehesten nackt schlafen?',
    'Wer würde am ehesten Dessous tragen?',
    'Wer würde am ehesten einen Körperteil piercen lassen?',
    'Wer würde am ehesten ein Liebes-Tattoo stechen lassen?',
    'Wer würde am ehesten den Expartner stalken auf Social Media?',
    'Wer würde am ehesten jealousy posts machen?',
    'Wer würde am ehesten revenge body bekommen?',
    'Wer würde am ehesten dramatisch Schluss machen?',
    'Wer würde am ehesten einen Korb geben?',
    'Wer würde am ehesten einen Korb bekommen?',
    'Wer würde am ehesten jemand Jüngeres daten?',
    'Wer würde am ehesten jemand Älteres daten?',
    'Wer würde am ehesten den Chef attraktiv finden?',
    'Wer würde am ehesten eine Office Romance haben?',
    'Wer würde am ehesten beim Flirten übertreiben?',
    'Wer würde am ehesten Champagner im Bett trinken?',
    'Wer würde am ehesten Erdbeeren und Sahne im Bett essen?',
    'Wer würde am ehesten sexy Kostüme tragen?',
    'Wer würde am ehesten in Leder oder Lack erscheinen?',
    'Wer würde am ehesten Partner Swapping ausprobieren?',
    'Wer würde am ehesten auf einer Swingerparty landen?',
    'Wer würde am ehesten BDSM ausprobieren?',
    'Wer würde am ehesten Fesseln benutzen?',
    'Wer würde am ehesten Augenbinden sexy finden?',
    'Wer würde am ehesten Eiswürfel im Bett benutzen?',
    'Wer würde am ehesten Schlagsahne im Bett benutzen?',
    'Wer würde am ehesten Schokoladensauce ablecken?',
    'Wer würde am ehesten Honig im Bett benutzen?',
    'Wer würde am ehesten Federn benutzen?',
    'Wer würde am ehesten Massage-Öl benutzen?',
    'Wer würde am ehesten Kerzen im Schlafzimmer anzünden?',
    'Wer würde am ehesten romantische Musik beim Sex spielen?',
    'Wer würde am ehesten laute Musik beim Sex spielen?',
    'Wer würde am ehesten Spiegel im Schlafzimmer haben?',
    'Wer würde am ehesten vor dem Spiegel posieren?',
    'Wer würde am ehesten sexy Selfies machen?',
    'Wer würde am ehesten Boudoir Fotos machen lassen?',
    'Wer würde am ehesten aktive Wäsche kaufen?',
    'Wer würde am ehesten den Partner überraschen?',
    'Wer würde am ehesten Frühstück im Bett machen?',
    'Wer würde am ehesten den ganzen Tag im Bett bleiben?',
    'Wer würde am ehesten Sekt im Bett trinken?',
    'Wer würde am ehesten Rose petals aufs Bett streuen?',
    'Wer würde am ehesten Liebesbriefe schreiben?',
    'Wer würde am ehesten Gedichte für den Partner schreiben?',
    'Wer würde am ehesten ein Lied für den Partner singen?',
    'Wer würde am ehesten öffentlich Zuneigung zeigen?',
    'Wer würde am ehesten ständig Händchen halten?',
    'Wer würde am ehesten matching Outfits tragen?',
    'Wer würde am ehesten Pärchen-Tattoos stechen?',
    'Wer würde am ehesten den Partner auf Social Media zeigen?',
    'Wer würde am ehesten die Beziehung geheim halten?',
    'Wer würde am ehesten mit dem besten Freund des Partners flirten?',
    'Wer würde am ehesten den Partner eifersüchtig machen?',
    'Wer würde am ehesten das Handy des Partners checken?',
    'Wer würde am ehesten durch das Telefon des Partners schauen?',
    'Wer würde am ehesten die Passwörter des Partners kennen wollen?',
    'Wer würde am ehesten den Standort des Partners tracken?',
    'Wer würde am ehesten verdächtige Nachrichten finden?',
    'Wer würde am ehesten eine Trap stellen?',
    'Wer würde am ehesten den Partner testen?',
    'Wer würde am ehesten Fake Profile erstellen?',
    'Wer würde am ehesten catfishen?',
    'Wer würde am ehesten gecatfished werden?',
    'Wer würde am ehesten Fake Bilder benutzen?',
    'Wer würde am ehesten über das Alter lügen?',
    'Wer würde am ehesten über den Job lügen?',
    'Wer würde am ehesten über das Einkommen lügen?',
    'Wer würde am ehesten angeben beim Date?',
    'Wer würde am ehesten zu teure Restaurants wählen?',
    'Wer würde am ehesten beim Date nichts essen?',
    'Wer würde am ehesten nervös beim Date sein?',
    'Wer würde am ehesten zu viel trinken beim Date?',
    'Wer würde am ehesten das Date vorzeitig verlassen?',
    'Wer würde am ehesten mitten im Date einschlafen?',
    'Wer würde am ehesten während des Dates am Handy sein?',
    'Wer würde am ehesten den Ex beim Date erwähnen?',
    'Wer würde am ehesten über Exen beim Date sprechen?',
    'Wer würde am ehesten die Mutter beim ersten Date mitbringen?',
    'Wer würde am ehesten die Freunde zum Date einladen?',
    'Wer würde am ehesten das Date stalken vorher?',
    'Wer würde am ehesten Google Recherche vor dem Date machen?',
    'Wer würde am ehesten Background Checks machen?',
    'Wer würde am ehesten zu schnell ernst werden?',
    'Wer würde am ehesten schon beim ersten Date von Kindern reden?',
    'Wer würde am ehesten beim ersten Date von Heirat reden?',
    'Wer würde am ehesten den Partner den Eltern vorstellen?',
    'Wer würde am ehesten zusammenziehen nach einer Woche?',
    'Wer würde am ehesten nach einem Monat verloben?',
    'Wer würde am ehesten impulsiv heiraten?',
    'Wer würde am ehesten Scheidung einreichen?',
    'Wer würde am ehesten das Haus behalten nach der Trennung?',
    'Wer würde am ehesten Rache an dem Ex nehmen?',
    'Wer würde am ehesten die Sachen des Ex verbrennen?',
    'Wer würde am ehesten die Sachen des Ex wegwerfen?',
    'Wer würde am ehesten die Sachen des Ex verkaufen?',
    'Wer würde am ehesten traurige Musik nach der Trennung hören?',
    'Wer würde am ehesten tagelang weinen nach der Trennung?',
    'Wer würde am ehesten Eiscreme essen nach der Trennung?',
    'Wer würde am ehesten sofort wieder daten nach der Trennung?',
    'Wer würde am ehesten einen Rebound haben?',
    'Wer würde am ehesten Sex zur Ablenkung haben?',
    'Wer würde am ehesten betrunken den Ex anrufen?',
    'Wer würde am ehesten betrunken zum Ex fahren?',
    'Wer würde am ehesten vor dem Haus des Ex stehen?',
    'Wer würde am ehesten peinliche Sprachnachrichten senden?',
    'Wer würde am ehesten peinliche Textnachrichten senden?',
    'Wer würde am ehesten Love Bombing betreiben?',
    'Wer würde am ehesten Blumen und Geschenke übertreiben?',
    'Wer würde am ehesten zu klingy sein?',
    'Wer würde am ehesten zu distanziert sein?',
    'Wer würde am ehesten Bindungsangst haben?',
    'Wer würde am ehesten Verlustangst haben?',
    'Wer würde am ehesten toxic Beziehungen anziehen?',
    'Wer würde am ehesten in einer toxischen Beziehung bleiben?',
    'Wer würde am ehesten Gaslighting nicht erkennen?',
    'Wer würde am ehesten manipuliert werden?',
    'Wer würde am ehesten manipulieren?',
    'Wer würde am ehesten emotionale Erpressung betreiben?',
    'Wer würde am ehesten mit Trennung drohen?',
    'Wer würde am ehesten Ultimatums stellen?',
    'Wer würde am ehesten den Partner kontrollieren?',
    'Wer würde am ehesten kontrolliert werden?',
    'Wer würde am ehesten die Finanzen des Partners kontrollieren?',
    'Wer würde am ehesten gemeinsames Konto wollen?',
    'Wer würde am ehesten getrennte Konten wollen?',
    'Wer würde am ehesten heimlich Geld ausgeben?',
    'Wer würde am ehesten Schulden vor dem Partner verheimlichen?',
    'Wer würde am ehesten ein Doppelleben führen?',
    'Wer würde am ehesten eine zweite Familie haben?',
    'Wer würde am ehesten lügen können ohne rot zu werden?',
    'Wer würde am ehesten ein Pokerface haben?',
    'Wer würde am ehesten alles ins Gesicht geschrieben haben?',
    'Wer würde am ehesten transparent sein?',
    'Wer würde am ehesten offene Kommunikation bevorzugen?',
    'Wer würde am ehesten Konflikte vermeiden?',
    'Wer würde am ehesten Streit anfangen?',
    'Wer würde am ehesten laut streiten?',
    'Wer würde am ehesten die Stimme erheben?',
    'Wer würde am ehesten Dinge werfen beim Streit?',
    'Wer würde am ehesten Türen knallen?',
    'Wer würde am ehesten das Haus verlassen beim Streit?',
    'Wer würde am ehesten im Auto schlafen nach Streit?',
    'Wer würde am ehesten bei den Eltern einziehen nach Streit?',
    'Wer würde am ehesten bei Freunden übernachten nach Streit?',
    'Wer würde am ehesten als erstes nachgeben?',
    'Wer würde am ehesten nie nachgeben?',
    'Wer würde am ehesten sich entschuldigen?',
    'Wer würde am ehesten nie sich entschuldigen?',
    'Wer würde am ehesten Blumen zur Versöhnung kaufen?',
    'Wer würde am ehesten Geschenke zur Versöhnung machen?',
    'Wer würde am ehesten Versöhnungssex haben?',
    'Wer würde am ehesten heimlich Sachen des Partners lesen?',
    'Wer würde am ehesten Tagebuch des Partners lesen?',
    'Wer würde am ehesten E-Mails des Partners lesen?',
    'Wer würde am ehesten DMs des Partners checken?',
    'Wer würde am ehesten den Browser-Verlauf checken?',
    'Wer würde am ehesten den Inkognito-Modus benutzen?',
    'Wer würde am ehesten eine geheime E-Mail haben?',
    'Wer würde am ehesten ein geheimes Handy haben?',
    'Wer würde am ehesten geheime Social Media Accounts haben?',
    'Wer würde am ehesten Finsta haben?',
    'Wer würde am ehesten anonyme Accounts haben?',
    'Wer würde am ehesten unter falschem Namen posten?',
    'Wer würde am ehesten Hate Comments schreiben?',
    'Wer würde am ehesten trollen im Internet?',
    'Wer würde am ehesten Catcalling betreiben?',
    'Wer würde am ehesten unangemessene Kommentare machen?',
    'Wer würde am ehesten zu direkt sein?',
    'Wer würde am ehesten zu schüchtern sein?',
    'Wer würde am ehesten nie den ersten Schritt machen?',
    'Wer würde am ehesten immer den ersten Schritt machen?',
    'Wer würde am ehesten aggressiv flirten?',
    'Wer würde am ehesten subtil flirten?',
    'Wer würde am ehesten Signale nicht verstehen?',
    'Wer würde am ehesten zu viele Signale senden?',
    'Wer würde am ehesten mixed Signals senden?',
    'Wer würde am ehesten Hot and Cold spielen?',
  ],
};

export const VIBES: VibeOption[] = [
  { id: 'party', name: 'Party', icon: '🎉', color: '#FF6B35' },
  { id: 'date_night', name: 'Date Night', icon: '💕', color: '#F72C25' },
  { id: 'family', name: 'Family', icon: '👨‍👩‍👧‍👦', color: '#10B981' },
  { id: 'spicy', name: 'Spicy', icon: '🌶️', color: '#F59E0B', isPremium: true },
];

export const DUMMY_ROOM_CODE = 'ABC123';

export const DUMMY_RESULTS = [
  { playerId: '1', playerName: 'FireStarter', votes: 5, percentage: 50 },
  { playerId: '2', playerName: 'CoolCat', votes: 3, percentage: 30 },
  { playerId: '3', playerName: 'PartyKing', votes: 2, percentage: 20 },
  { playerId: '4', playerName: 'NightOwl', votes: 0, percentage: 0 },
];
