-- Migration: Seed English BUSTED! questions
-- Description: Add English translations of all questions for language support

-- ============================================
-- PARTY VIBE (Fun, lighthearted questions) - English
-- ============================================
INSERT INTO busted_questions (vibe, text, is_premium, language) VALUES
('party', 'Who would most likely storm the stage at a karaoke session?', false, 'en'),
('party', 'Who would most likely suggest a spontaneous road trip with no destination?', false, 'en'),
('party', 'Who would most likely be the first one on the dance floor?', false, 'en'),
('party', 'Who would most likely find the first clue in an escape room?', false, 'en'),
('party', 'Who would most likely be the first to drop out of a drinking game?', false, 'en'),
('party', 'Who would most likely party all night long?', false, 'en'),
('party', 'Who would most likely get a strike while bowling?', false, 'en'),
('party', 'Who would most likely perform at a talent show?', false, 'en'),
('party', 'Who would most likely invent an embarrassing dance move?', false, 'en'),
('party', 'Who would most likely make friends with strangers at a party?', false, 'en'),
('party', 'Who would most likely win at Beer Pong?', false, 'en'),
('party', 'Who would most likely throw a spontaneous party at their place?', false, 'en'),
('party', 'Who would most likely DJ at a party?', false, 'en'),
('party', 'Who would most likely win at limbo dancing?', false, 'en'),
('party', 'Who would most likely fall asleep at a party?', false, 'en'),
('party', 'Who would most likely ask the DJ for a special song?', false, 'en'),
('party', 'Who would most likely go to an after-party?', false, 'en'),
('party', 'Who would most likely strike the best pose at a photo shoot?', false, 'en'),
('party', 'Who would most likely wear the best costume at a themed party?', false, 'en'),
('party', 'Who would most likely shine as MVP at Flunkyball?', false, 'en'),
('party', 'Who would most likely lead a conga line?', false, 'en'),
('party', 'Who would most likely tell the wildest stories during Never Have I Ever?', false, 'en'),
('party', 'Who would most likely be drunk after just 2 drinks?', false, 'en'),
('party', 'Who would most likely lose their phone at a party?', false, 'en'),
('party', 'Who would most likely be the last one to get home in the morning?', false, 'en'),
-- Additional party questions from beerpong.de
('party', 'Who would most likely push a kid?', false, 'en'),
('party', 'Who would most likely fart and blame it on someone else?', false, 'en'),
('party', 'Who would most likely wear the same underwear twice?', false, 'en'),
('party', 'Who would most likely pee in the shower?', false, 'en'),
('party', 'Who would most likely pick their nose and eat it?', false, 'en'),
('party', 'Who would most likely assume a different identity while on vacation?', false, 'en'),
('party', 'Who would most likely troll people online?', false, 'en'),
('party', 'Who would most likely create and use a fake account?', false, 'en'),
('party', 'Who would most likely enjoy their own fart?', false, 'en'),
('party', 'Who would most likely cry during a movie?', false, 'en'),
('party', 'Who would most likely shave off their eyebrows while drunk?', false, 'en'),
('party', 'Who would most likely get scammed online?', false, 'en'),
('party', 'Who would most likely scam someone online?', false, 'en'),
('party', 'Who would most likely pretend to understand a joke?', false, 'en'),
('party', 'Who would most likely go to the movies alone?', false, 'en'),
('party', 'Who would most likely Google a walkthrough while gaming?', false, 'en'),
('party', 'Who would most likely shoplift?', false, 'en'),
('party', 'Who would most likely get arrested for public disturbance?', false, 'en'),
('party', 'Who would most likely go without makeup?', false, 'en'),
('party', 'Who would most likely go a month without alcohol?', false, 'en'),
('party', 'Who would most likely kiss a stranger?', false, 'en'),
('party', 'Who would most likely do a bungee jump?', false, 'en'),
('party', 'Who would most likely delete their Instagram account?', false, 'en'),
('party', 'Who would most likely eat only fast food for a month?', false, 'en'),
('party', 'Who would most likely drink hot dog water for money?', false, 'en'),
('party', 'Who would most likely talk on the phone while on the toilet?', false, 'en'),
('party', 'Who would most likely get cosmetic surgery?', false, 'en'),
('party', 'Who would most likely go all out at a Schlager party?', false, 'en'),
('party', 'Who would most likely steal ice cream from a kid?', false, 'en'),
('party', 'Who would most likely participate in a dating show?', false, 'en'),
('party', 'Who would most likely dye their hair green?', false, 'en'),
('party', 'Who would most likely become part of a reality show?', false, 'en'),
('party', 'Who would most likely freeze to death on Mount Everest?', false, 'en'),
('party', 'Who would most likely spend a night with Justin Bieber?', false, 'en'),
('party', 'Who would most likely go two weeks without brushing their teeth?', false, 'en'),
('party', 'Who would most likely end up in jail after a fight?', false, 'en'),
('party', 'Who would most likely pursue a criminal career?', false, 'en'),
('party', 'Who would most likely move into the wilderness?', false, 'en'),
('party', 'Who would most likely not shower for a week?', false, 'en'),
('party', 'Who would most likely shave their head?', false, 'en'),
('party', 'Who would most likely appear on trash TV?', false, 'en'),
('party', 'Who would most likely quit social media?', false, 'en'),
('party', 'Who would most likely survive a zombie apocalypse?', false, 'en'),
('party', 'Who would most likely go a month without their smartphone?', false, 'en'),
('party', 'Who would most likely get someone pregnant or get pregnant?', false, 'en'),
('party', 'Who would most likely get a tattoo while drunk?', false, 'en'),
('party', 'Who would most likely do tequila with salt up the nose and lime in the eye?', false, 'en'),
('party', 'Who would most likely play Beer Pong with only shots?', false, 'en'),
('party', 'Who would most likely chug a liter of beer?', false, 'en'),
('party', 'Who would most likely run naked around the house?', false, 'en'),
('party', 'Who would most likely take off their shirt right now?', false, 'en'),
('party', 'Who would most likely call their parents and tell them they are having a baby?', false, 'en'),
('party', 'Who would most likely fake an orgasm?', false, 'en'),
('party', 'Who would most likely be a disappointment in bed?', false, 'en'),
('party', 'Who would most likely propose to a stranger?', false, 'en'),
('party', 'Who would most likely lick a strangers ear?', false, 'en'),
('party', 'Who would most likely post their phone number on social media?', false, 'en'),
('party', 'Who would most likely cut a hole in their shirt?', false, 'en'),
('party', 'Who would most likely burn their underwear?', false, 'en'),
('party', 'Who would most likely cheat on their partner?', false, 'en'),
('party', 'Who would most likely keep secrets from their partner?', false, 'en'),
('party', 'Who would most likely think of someone else during sex?', false, 'en'),
('party', 'Who would most likely turn the kids against their partner?', false, 'en'),
('party', 'Who would most likely fight unfairly during an argument?', false, 'en'),
('party', 'Who would most likely surprise their partner with breakfast in bed?', false, 'en'),
('party', 'Who would most likely plan a surprise vacation?', false, 'en'),
('party', 'Who would most likely go partying without their partner?', false, 'en'),
('party', 'Who would most likely eat their partners candy?', false, 'en'),
('party', 'Who would most likely forget their partners birthday?', false, 'en'),
('party', 'Who would most likely forget their anniversary?', false, 'en'),
('party', 'Who would most likely spoil their partner with a 3-course meal?', false, 'en'),
('party', 'Who would most likely give their partner a spontaneous lap dance?', false, 'en'),
('party', 'Who would most likely gossip about their partner with friends?', false, 'en'),
('party', 'Who would most likely talk about their partner constantly?', false, 'en'),
('party', 'Who would most likely call their partner their best friend?', false, 'en'),
('party', 'Who would most likely go overboard while partying?', false, 'en'),
('party', 'Who would most likely gamble away money at a casino?', false, 'en'),
('party', 'Who would most likely commit a crime for their family?', false, 'en'),
('party', 'Who would most likely give up a hobby for their partner?', false, 'en'),
('party', 'Who would most likely survive without water and electricity?', false, 'en'),
('party', 'Who would most likely quit their job and follow their passion?', false, 'en'),
('party', 'Who would most likely turn off their smartphone for a month?', false, 'en'),
('party', 'Who would most likely not gossip for a year?', false, 'en'),
('party', 'Who would most likely make a change in politics?', false, 'en'),
('party', 'Who would most likely go to a silent monastery?', false, 'en'),
('party', 'Who would most likely go vegan?', false, 'en'),
('party', 'Who would most likely use their lifetime to make the world better?', false, 'en'),
('party', 'Who would most likely help a stranger with their problems?', false, 'en'),
('party', 'Who would most likely write a surprising book?', false, 'en'),
('party', 'Who would most likely live without a car?', false, 'en'),
('party', 'Who would most likely record a deep podcast?', false, 'en'),
('party', 'Who would most likely go on an educational journey?', false, 'en'),
('party', 'Who would most likely actively fight against deforestation?', false, 'en'),
('party', 'Who would most likely collect trash at the beach?', false, 'en'),
('party', 'Who would most likely publicly stand up against racism?', false, 'en'),
('party', 'Who would most likely avoid unnecessary consumption?', false, 'en'),
('party', 'Who would most likely donate 10% of their income?', false, 'en'),
('party', 'Who would most likely free animals from captivity?', false, 'en'),
('party', 'Who would most likely take care of elderly people despite sacrifices?', false, 'en'),
('party', 'Who would most likely collect trash in the forest?', false, 'en'),
('party', 'Who would most likely write a bestselling book?', false, 'en'),
('party', 'Who would most likely banish the other to the couch?', false, 'en'),
('party', 'Who would most likely take care of the kids?', false, 'en'),
('party', 'Who would most likely hog the bathroom in the morning?', false, 'en'),
('party', 'Who would most likely wreck the shared car?', false, 'en'),
('party', 'Who would most likely start a fight with the neighbors?', false, 'en'),
('party', 'Who would most likely let personal hygiene slide after the wedding?', false, 'en'),
('party', 'Who would most likely still be romantic after years?', false, 'en'),
('party', 'Who would most likely give beautiful gifts?', false, 'en'),
('party', 'Who would most likely get jealous over little things?', false, 'en'),
('party', 'Who would most likely run the household?', false, 'en'),
('party', 'Who would most likely stop working?', false, 'en'),
('party', 'Who would most likely still party in retirement?', false, 'en'),
('party', 'Who would most likely gain weight after the wedding?', false, 'en'),
('party', 'Who would most likely throw money out the window?', false, 'en'),
('party', 'Who would most likely suddenly become rich?', false, 'en'),
('party', 'Who would most likely spoil the kids?', false, 'en'),
('party', 'Who would most likely throw a spontaneous champagne breakfast?', false, 'en');

-- ============================================
-- DATE NIGHT VIBE (Romantic questions) - English
-- ============================================
INSERT INTO busted_questions (vibe, text, is_premium, language) VALUES
('date_night', 'Who would most likely plan a romantic candlelit dinner?', false, 'en'),
('date_night', 'Who would most likely make a good impression on a first date?', false, 'en'),
('date_night', 'Who would most likely make the first move?', false, 'en'),
('date_night', 'Who would most likely write a love poem?', false, 'en'),
('date_night', 'Who would most likely cry during a romantic movie?', false, 'en'),
('date_night', 'Who would most likely make a grand romantic gesture?', false, 'en'),
('date_night', 'Who would most likely be nervous on a date?', false, 'en'),
('date_night', 'Who would most likely write a love letter?', false, 'en'),
('date_night', 'Who would most likely go on a blind date?', false, 'en'),
('date_night', 'Who would most likely propose at sunset?', false, 'en'),
('date_night', 'Who would most likely surprise their partner with breakfast in bed?', false, 'en'),
('date_night', 'Who would most likely organize a picnic in the park?', false, 'en'),
('date_night', 'Who would most likely take a couples dance class?', false, 'en'),
('date_night', 'Who would most likely book a weekend in Paris?', false, 'en'),
('date_night', 'Who would most likely pay the bill on a date?', false, 'en'),
('date_night', 'Who would most likely choose a starry sky for a date?', false, 'en'),
('date_night', 'Who would most likely create a playlist for a romantic dinner?', false, 'en'),
('date_night', 'Who would most likely talk about ex-partners on a date?', false, 'en'),
('date_night', 'Who would most likely dedicate a love song on the radio?', false, 'en'),
('date_night', 'Who would most likely swipe right on Tinder without reading the profile?', false, 'en'),
('date_night', 'Who would most likely bring a partner home to meet the parents?', false, 'en'),
('date_night', 'Who would most likely start a relationship through dating apps?', false, 'en'),
('date_night', 'Who would most likely want a matching tattoo with their partner?', false, 'en'),
('date_night', 'Who would most likely say "I love you" first?', false, 'en'),
('date_night', 'Who would most likely forget about a date?', false, 'en');

-- ============================================
-- FAMILY VIBE (Safe, wholesome questions) - English
-- ============================================
INSERT INTO busted_questions (vibe, text, is_premium, language) VALUES
('family', 'Who would most likely overeat at a family dinner?', false, 'en'),
('family', 'Who would most likely be the first one out in Monopoly?', false, 'en'),
('family', 'Who would most likely find the best hiding spot in hide and seek?', false, 'en'),
('family', 'Who would most likely not be able to smile in a family photo?', false, 'en'),
('family', 'Who would most likely have to ask for directions on a road trip?', false, 'en'),
('family', 'Who would most likely turn the kitchen into chaos while baking?', false, 'en'),
('family', 'Who would most likely score first at a family quiz?', false, 'en'),
('family', 'Who would most likely tell a joke that nobody laughs at?', false, 'en'),
('family', 'Who would most likely play the grill master at a BBQ?', false, 'en'),
('family', 'Who would most likely want to adopt a pet?', false, 'en'),
('family', 'Who would most likely forget where the car is parked?', false, 'en'),
('family', 'Who would most likely win at a board game night?', false, 'en'),
('family', 'Who would most likely sing the wrong melody at karaoke?', false, 'en'),
('family', 'Who would most likely plan a family vacation?', false, 'en'),
('family', 'Who would most likely fall asleep during a movie?', false, 'en'),
('family', 'Who would most likely play an instrument in a band?', false, 'en'),
('family', 'Who would most likely run a marathon?', false, 'en'),
('family', 'Who would most likely learn a new language?', false, 'en'),
('family', 'Who would most likely light a campfire while camping?', false, 'en'),
('family', 'Who would most likely want the most siblings?', false, 'en'),
('family', 'Who would most likely be late to a family gathering?', false, 'en'),
('family', 'Who would most likely buy the best Christmas gift?', false, 'en'),
('family', 'Who would most likely say grace at a family dinner?', false, 'en'),
('family', 'Who would most likely keep family traditions alive?', false, 'en'),
('family', 'Who would most likely create a family tree?', false, 'en');

-- ============================================
-- SPICY VIBE (Bold, provocative questions - 18+) - English
-- ============================================
INSERT INTO busted_questions (vibe, text, is_premium, language) VALUES
('spicy', 'Who would most likely have an affair?', false, 'en'),
('spicy', 'Who would most likely go home with someone on the first date?', false, 'en'),
('spicy', 'Who would most likely have a one-night stand?', false, 'en'),
('spicy', 'Who would most likely make out with someone at a club?', false, 'en'),
('spicy', 'Who would most likely give out their phone number at a party?', false, 'en'),
('spicy', 'Who would most likely send a sexy photo?', false, 'en'),
('spicy', 'Who would most likely get caught in public?', false, 'en'),
('spicy', 'Who would most likely have friends with benefits?', false, 'en'),
('spicy', 'Who would most likely take back an ex?', false, 'en'),
('spicy', 'Who would most likely take the initiative when flirting?', false, 'en'),
('spicy', 'Who would most likely have a long-distance relationship?', false, 'en'),
('spicy', 'Who would most likely cheat in a relationship?', false, 'en'),
('spicy', 'Who would most likely become a stripper?', false, 'en'),
('spicy', 'Who would most likely have three dates in one week?', false, 'en'),
('spicy', 'Who would most likely try an open relationship?', false, 'en'),
('spicy', 'Who would most likely want to sleep with a celebrity?', false, 'en'),
('spicy', 'Who would most likely get picked up at a bar?', false, 'en'),
('spicy', 'Who would most likely get a tattoo of their partners name?', false, 'en'),
('spicy', 'Who would most likely call someone after a wild night out?', false, 'en'),
('spicy', 'Who would most likely stay overnight on a first date?', false, 'en'),
('spicy', 'Who would most likely have a sugar daddy or sugar mommy?', false, 'en'),
('spicy', 'Who would most likely always choose "dare" in Truth or Dare?', false, 'en'),
('spicy', 'Who would most likely act in a movie with a bedroom scene?', false, 'en'),
('spicy', 'Who would most likely go skinny dipping?', false, 'en'),
('spicy', 'Who would most likely kiss someone from this group?', false, 'en'),
-- Additional spicy questions from beerpong.de
('spicy', 'Who would most likely have a threesome with two women?', false, 'en'),
('spicy', 'Who would most likely have a threesome with two men?', false, 'en'),
('spicy', 'Who would most likely participate in an orgy?', false, 'en'),
('spicy', 'Who would most likely cheat on their partner while on vacation?', false, 'en'),
('spicy', 'Who would most likely have sex on the beach?', false, 'en'),
('spicy', 'Who would most likely visit a swinger club?', false, 'en'),
('spicy', 'Who would most likely live in an open relationship?', false, 'en'),
('spicy', 'Who would most likely start a secret affair?', false, 'en'),
('spicy', 'Who would most likely try BDSM?', false, 'en'),
('spicy', 'Who would most likely have sex in public?', false, 'en'),
('spicy', 'Who would most likely sleep with someone they dont like?', false, 'en'),
('spicy', 'Who would most likely spend a night with someone hoping for benefits?', false, 'en'),
('spicy', 'Who would most likely have sex in their parents bed?', false, 'en'),
('spicy', 'Who would most likely kiss someone of the same gender?', false, 'en'),
('spicy', 'Who would most likely build a collection of sex toys?', false, 'en'),
('spicy', 'Who would most likely try a sex swing?', false, 'en'),
('spicy', 'Who would most likely regularly watch porn?', false, 'en'),
('spicy', 'Who would most likely make a porn video?', false, 'en'),
('spicy', 'Who would most likely have a foot fetish?', false, 'en'),
('spicy', 'Who would most likely serve as a sex slave?', false, 'en'),
('spicy', 'Who would most likely do an erotic photoshoot?', false, 'en'),
('spicy', 'Who would most likely get whipped?', false, 'en'),
('spicy', 'Who would most likely tell a wild sex story?', false, 'en'),
('spicy', 'Who would most likely clean naked for money?', false, 'en');

-- ============================================
-- Update statistics
-- ============================================
ANALYZE busted_questions;

-- Count questions by language
DO $$
DECLARE
  de_count INTEGER;
  en_count INTEGER;
  total_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO de_count FROM busted_questions WHERE language = 'de';
  SELECT COUNT(*) INTO en_count FROM busted_questions WHERE language = 'en';
  SELECT COUNT(*) INTO total_count FROM busted_questions;

  RAISE NOTICE 'BUSTED! Questions after English seed:';
  RAISE NOTICE '  German (de): % questions', de_count;
  RAISE NOTICE '  English (en): % questions', en_count;
  RAISE NOTICE '  Total: % questions', total_count;
END $$;
